### ISSUE TITLE
elements always chooses first or last element of non empty array

### ISSUE THREAD

**Issue by mikesol** [purescript/purescript-quickcheck#108]
Theoretically, the test below should not pass because it checks to see if the output is only `'_'` or `'d'`, which has a very low probability of success over 100 tests. However, on my version of quickcehck/purescript/linux it does succeed. I could also be constructing the test wrong, but I believe it does show a bug.

quickcheck: 6.1.0
purescript: 0.13.8
linux: Ubuntu 18.04.4 LTS

```purescript
module Test.Main where

import Prelude
import Control.Monad.Gen (elements)
import Data.NonEmpty (NonEmpty(..))
import Effect (Effect)
import Test.QuickCheck (Result(..), quickCheck)
import Test.QuickCheck.Gen (Gen)

g :: Gen Result
g = do
  a <- elements $ NonEmpty '_' ([ 'a', 'b', 'c', 'd' ])
  pure (if (a /= '_' && a /= 'd') then Failed $ "got a b or c: " <> (show a) else Success)

main :: Effect Unit
main = do
  quickCheck g
```

**Comment by garyb** [comment]
Thanks for the report! This is a bug in `purescript-gen` rather than QC, there's a PR open that should fix it: https://github.com/purescript/purescript-gen/pull/23

**Comment by JordanMartinez** [comment]
The underlying bug was fixed. This issue can be closed.
