### ISSUE TITLE
frequency uses NonEmptyList, oneOf uses NonEmptyArray 

### ISSUE THREAD

**Issue by drathier** [purescript/purescript-quickcheck#128]
It's a real road-bump that these two don't accept the same type. Switching from `oneOf` to `frequency` shouldn't require me to add a new import and use a different list type.

https://github.com/purescript/purescript-quickcheck/blob/v7.1.0/src/Test/QuickCheck/Gen.purs#L158-L166

**Comment by JordanMartinez** [comment]
I'm adding this as a breaking change.
