### ISSUE TITLE
Confused about quickcheck run output

### ISSUE THREAD

**Issue by lazywithclass** [purescript/purescript-quickcheck#19]
First of all thanks for this project!

I'm going through the exercises proposed in https://leanpub.com/purescript/read, I'm also trying to write tests for all of them using quickcheck.

You can see an example of what I'm trying to do:

[source link](https://github.com/lazywithclass/purescript-by-example-exercises/blob/dac52b85c0bd59adfae895bbe0a16ae27b4a2eba/src/Exercises/2.purs)

``` purescript
module Exercises.Chapters.Two where

import Math

circleArea r = Math.pi * r 
```

[test link](https://github.com/lazywithclass/purescript-by-example-exercises/blob/694c4df61422d63e567d97e5824cf3a15c6f0732/tests/Tests.purs)

``` purescript
module Main where

import Debug.Trace
import Exercises.Chapters.Two
import Test.QuickCheck
import Math

main = do

  quickCheck $ \r -> (circleArea r) / r == Math.pi
```

When I run tests with `grunt` (I created the project following https://leanpub.com/purescript/read#leanpub-auto-using-grunt-project-templates) I get this error:

```
Error: Test 17 failed: 
Test returned false
    at Object.error (/home/vagrant/workspace/purescript-by-examples-exercises/tmp/node_modules/Control.Monad.Eff.Exception/index.js:11:12)
```

I thought that `17` is the simplest scenario that leads to a red test, but if I run `(circleArea 17) / 17 == Math.pi` in `psci` I get true, so I'm probably wrong with that assumption.

I'm sorry if the error is trivial but I'm just beginning to learn PureScript and quickcheck, any hint is really appreciated!

Happy new year :D

**Comment by joneshf** [comment]
We don't have shrinking yet. That would help immensely here.

**Comment by joneshf** [comment]
But you can annotate the test with `(<?>)`.

**Comment by lazywithclass** [comment]
I see, sadly I don't have any experience to help you in this.

What would `(<?>)` allow me to do?

**Comment by beckyconning** [comment]
<?> allows you to provide a message for when the test fails

**Comment by JordanMartinez** [comment]
This issue is largely a question that was answered. Closing.
