### ISSUE TITLE
`oneOf` and `elements` never yield the last element

### ISSUE THREAD

**Issue by sharkdp** [purescript/purescript-quickcheck#31]
Currently, `oneOf` is implemented as
```purescript
oneOf :: forall a. Gen a -> Array (Gen a) -> Gen a
oneOf x xs = do
  n <- chooseInt zero (length xs)
  if n < one then x else fromMaybe x (xs !! (n - one))
```
Apparently, `chooseInt a b` returns a random integer from the set `a, a + 1, ..., b - 1`, excluding the value `b`. Consequently, the maximum value for the index `n - one` in the last line is `length xs - 2` and the last element of `xs` will never be chosen:

``` purescript
> showSample (oneOf (pure 1) [pure 2])
[1,1,1,1,1,1,1,1,1,1]
```

The same is true for `elements`.

**Comment by paf31** [comment]
:+1: Thanks!
