### ISSUE TITLE
Faulty LCG due to floating point errors

### ISSUE THREAD

**Issue by sharkdp** [purescript/purescript-quickcheck#32]
I was pretty surprised to see this:
```purescript
> showSample' 200 (chooseInt 0 2)
[0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0]
```
Either I am extremely unlucky in throwing coins or something is seriously wrong with the random number generator.

Joking aside, it seems that `chooseInt` itself is fine but the LCG is strongly biased towards even numbers. Here is the first few numbers which are generated by `lcgNext`, starting from `seed = 0`:
```
0
12345
333190782
654583808
284506112
1064896576
143405824
222029632
1047996032
762745856
```
My guess is that this is due to integer overflows in the `lcgNext` function. To check this, I ported `lcgNext` to Mathematica and here is what I get:
```
0
12345
333190782
654583775
375725100
229283573
35593354
1051550459
220057368
794471793
```
Note that the first three numbers are the same. Subsequent results diverge.

Even stranger, the Mathematica version also seems hardly random. As far as I checked, the numbers have an alternating even/odd pattern... (??).

Mathematica code:
``` Mathematica
> lcgNext[n_] := Mod[1103515245 n + 12345, 1073741824]
> NestList[lcgNext, 0, 10]
{0, 12345, 333190782, 654583775, 375725100, 229283573, 35593354, \
1051550459, 220057368, 794471793, 551188310}
```

**Comment by garyb** [comment]
That's odd, the LCG uses `Number` internally and converts back to `Int` once it's done (or, is supposed to). I guess we're still making a mistake somewhere in there.

The LCG behaves horribly when you give it a seed of 0 by the way, that's probably why you're seeing poor results.

**Comment by sharkdp** [comment]
I have checked different seeds, too. I typically get around 0.6% (!) of odd numbers.

`sample` and `showSample` use `seed=0`, so I was assuming this would be fine. Maybe these functions should have a seed parameter or generate a random seed?

**Comment by sharkdp** [comment]
Okay, the alternating even/odd numbers are actually a property of LCGs where `m` is a power of 2 (`1073741824 = 2^30`):
https://en.wikipedia.org/wiki/Linear_congruential_generator#Advantages_and_disadvantages_of_LCGs

**Comment by sharkdp** [comment]
@garyb You are right. It is not an integer overflow but simply a problem with the JS floating point numbers:

In the third step (starting with a seed of `333190782`), the LCG performs the multiplication
`333190782 * 1103515245`.
With JavaScript floats, the result is
```
367681107430471600
```
while it should be
```
367681107430471590
```

A possible solution could be to choose a smaller-length cycle for the LCG?

**Comment by garyb** [comment]
Ugh. Yeah, I think that's worth exploring... the constants we have now come from Wikipedia I think :smile:, there are a few variations in there so perhaps there's something more suitable.

Alternatively we could switch to some other kind of PRNG that might not suffer the same issues I guess.

Thanks for looking into these issues, it explains a few things we've noticed about in the past but assumed were down to our `Arbitrary` instances rather than the quality of the LCG.

**Comment by hdgarrood** [comment]
Perhaps it's time to consider creating a wrapper around a JS arbitrary-precision integer library? GHCJS uses [jsbn](http://www-cs-students.stanford.edu/~tjw/jsbn/) so that's probably a good option.

**Comment by garyb** [comment]
Is this fixed now with #34 merged? It should be, I think? /cc @hdgarrood

**Comment by hdgarrood** [comment]
I think so, this is what I get now:
```
> map sum $ randomSample' 200 (chooseInt 0 1)
97
```

(`chooseInt` changed to include the upper bound since this issue was opened, I think)

**Comment by sharkdp** [comment]
@hdgarrood Thank you very much!

**Comment by sharkdp** [comment]
/cc @hdgarrood 

> Perhaps it's time to consider creating a wrapper around a JS arbitrary-precision integer library? GHCJS uses jsbn so that's probably a good option.

I have started working on a big integer library for purescript: https://github.com/sharkdp/purescript-bigints. It's just a simple wrapper around an existing library, as you suggested, but maybe you are interested..
