### ISSUE TITLE
Break out Gen into its own library?

### ISSUE THREAD

**Issue by jbrownson** [purescript/purescript-quickcheck#44]
Capturing here from a conversation in IRC.

It's a pretty handy Monad on its own right testing or not. Maybe it should be in its own library to be used outside of a testing context.

**Comment by hdgarrood** [comment]
I'm actually not a fan of this. There's nothing stopping you from using `Gen` in a non-testing context as things stand currently (in fact I have done so in `purescript-benchotron`), and if `Gen` were broken out into a separate library there would be almost nothing left here.

**Comment by garyb** [comment]
This already exists actually - https://github.com/purescript/purescript-gen
