### ISSUE TITLE
(Testable prop) => Testable (Gen prop)

### ISSUE THREAD

**Issue by DavidHarrison** [purescript/purescript-quickcheck#45]
Haskell's QuickCheck defines the [instance](http://hackage.haskell.org/package/QuickCheck-2.8.1/docs/Test-QuickCheck-Property.html#t:Testable)
```haskell
(Testable prop) => Testable (Gen prop)
```
When trying to define it for PureScript's QuickCheck, after expanding all of the type synonyms I get
```purescript
(Testable prop) => Testable (StateT Identity {newSeed :: Seed, size :: Int} prop)
```
which gives the error:
```
Type class instance head is invalid due to use of type

  ( size :: Int
  , newSeed :: Seed
  )

All types appearing in instance declarations must be of the form T a_1 .. a_n, where each type a_i is of the same form.
```

Have there been any thoughts on defining the instance?

**Comment by paf31** [comment]
:+1: I'd like to have this defined too. Maybe we need to change `Gen` into a `newtype`.
