### ISSUE TITLE
Add `forAll`

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-quickcheck#47]
From `Test.QuickCheck`:

``` haskell
forAll :: (Show a, Testable prop) => Gen a -> (a -> prop) -> Property
```

Essentially, this allows you to write quickCheck tests without relying on an `Arbitrary` instance for all of the arguments you need. This would help us avoid the problem of orphan Arbitrary instances. For instance:

``` purescript
quickCheck $ forAll (maps :: Gen (Map Int String))
                    (\m -> m == Map.fromUnfoldable (Map.toFoldable m))
```

or something. Then, we are free to put `Gen` values for any type anywhere, without all the `newtype` shenanigans. We can also freely parameterize `Gen` values based on other values that are only available at runtime, etc etc. I'm sure I've complained about these aspects of type classes before. ;)

**Comment by hdgarrood** [comment]
Another potentially motivating example:

```purescript
ints :: { min :: Int, max :: Int } -> Gen Int
```

**Comment by paf31** [comment]
:+1:

**Comment by rightfold** [comment]
purescript-reflection?

**Comment by paf31** [comment]
@rightfold Possibly, but I think it would be good to solve this with a combinator first. The `Testable Gen` instance is related too.
