### ISSUE TITLE
Add prefab properties for Prelude laws

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript-quickcheck#55]
It would be useful if this library had property constructors for the Prelude laws.

For example:

    eqReflexivity :: (Arbitrary a, Eq a) => a -> Boolean
    eqReflexivity = \x -> x == x

What do you think?

**Comment by garyb** [comment]
Have you seen this? https://github.com/garyb/purescript-quickcheck-laws

**Comment by rightfold** [comment]
Ah! Great! :D

**Comment by garyb** [comment]
It wasn't published on Pursuit for some reason, but it is now. Hopefully that will help with discoverability!
