### ISSUE TITLE
`elements` behavior and type inconsistent with documentation

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-quickcheck#64]
Documentation: "Create a random generator which selects a value from a non-empty collection with uniform probability."

Type: `forall a. a -> Array a -> Gen a`

The extra argument is surprising. For comparison, the type of this function in Haskell's QuickCheck is what one would expect:

`elements :: [a] -> Gen a`

It seems like one could trivially define an (unsafe) `elements'`that calls `elements` with the head and tail of a provided Array. Perhaps this should be provided?

**Comment by garyb** [comment]
The introduction of the extra argument is what guarantees the non-empty-ness of the collection here. We could use the `NonEmpty` type now, as I think that wasn't around when this combinator was introduced.

What's the issue here - that it demands proof of being non-empty, or just that it's defined in an unclear way with the extra argument?

**Comment by paf31** [comment]
Yes, let's use `NonEmpty`.

**Comment by matthewleon** [comment]
@garyb yes, to me as a library consumer it did not seem intuitive, given the current documentation, that the first argument is intended to be a witness to nonemptiness. In any case, it seems that `NonEmpty` can serve as an excellent solution. Thanks!

**Comment by matthewleon** [comment]
I'm happy to submit a PR for this, but I'm curious to know which approach you would prefer: making a breaking change to the type of `elements` or adding some new function?

**Comment by paf31** [comment]
I think the breaking change is fine, but we probably won't merge it until the next major release, which might be a while.
