### ISSUE TITLE
bizarre results from chooseInt

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-quickcheck#71]
A bit disturbing...

in psci:

```
> randomSample $ chooseInt bottom top                                                  │
[1,1,1,1,1,1,1,1,1,1]

> randomSample $ chooseInt (bottom + 1000) (top - 1000)
[-2147482556,-2147482322,-2147481034,-2147481207,-2147481873,-2147481935,-2147482411,-2147481471,-2147481069,-2147482542]
```

**Comment by matthewleon** [comment]
This is being caused by a nasty integer overflow. Seeing if there is a reasonable way to address this.

**Comment by matthewleon** [comment]
Here is the current code in `master`

```
chooseInt :: Int -> Int -> Gen Int
chooseInt a b = clamp <$> lcgStep
  where
  clamp :: Int -> Int
  clamp x = case x `mod` (b - a + one) of
              r | r >= 0 -> a + r
                | otherwise -> b + r + one
```

Three problems I see happening here:

1. `(b - a)` easily overflows, causing all kinds of trouble 
2. `lcgStep` always generates numbers that are modulus 2147483647 (2^31 - 1). But `Int` is a 32 bit type. We never flip that last bit.
3. `r` will always be positive. The `otherwise` case is dead code.

**Comment by hdgarrood** [comment]
Ouch, good find. Maybe we should keep these values as `Number` for slightly longer then?

**Comment by matthewleon** [comment]
Well, that approach solves problem 1, so it's definitely a start. It doesn't deal with issue 2 with `lcgStep` though. Looking into a few possible solutions to that, now. The least annoying one would involve rewriting `chooseInt` to rely on `choose`, or to just rely on `uniform` directly.

Of course, that raises the problem that `choose` itself has an overflow issue, as well...

**Comment by matthewleon** [comment]
(Unless what you mean is to convert `Test.QuickCheck.LCG` to use `Number` instead of `Int` in a bunch of places. That might work. Looking into it.)

**Comment by matthewleon** [comment]
Incorporating something like this might make the change easier: https://github.com/rgrempel/purescript-int-53

It's used in https://github.com/jystic/purescript-jack

**Comment by hdgarrood** [comment]
Yes, although we require that core libraries only depend on other core libraries. It's obviously not ideal but I think in this case I might just use `Number` and be careful not to do anything that could result in a non-integral value.

**Comment by matthewleon** [comment]
I feel like one of the upshots of this is that there should be some kind of test on the uniformity of `choose` and `chooseInt`. Is it worth throwing a chi-squared goodness-of-fit into the tests, or is that going too far? It seems easy for bugs like this to slip in unnoticed... At the very least, one could dump some histograms to the console or a file.

**Comment by hdgarrood** [comment]
Chi-squared should be easy enough to implement, that sounds good to me.

**Comment by matthewleon** [comment]
Another concern, while we're at it. If the solution involves changing the LCG values to be Numbers instead of Ints, that's a pretty significant breaking change, no? Would it be better to deprecate the old ones in some way alongside?

**Comment by hdgarrood** [comment]
Could we do it in a non breaking way by exporting new functions you can use in cases like this?

**Comment by matthewleon** [comment]
Probably, though from a documentation perspective I imagine it will be a bit awkward.

**Comment by matthewleon** [comment]
Adding a reference to this past discussion of a related issue: https://github.com/purescript/purescript-quickcheck/issues/32

**Comment by matthewleon** [comment]
Okay, after a lot of thought and wikipedia-ing, I feel pretty confused about how to go ahead.

1: The simplest option would be to admit defeat and just update the docs, warning the user that `chooseInt` has a limited range and will act very funky if given the wrong values.

2: Another option might be to scrap `chooseInt` in favor of something like `choose31BitInt` or `choosePositiveInt` or something of that sort, encoding the limitation in the type system and giving the user some ergonomic way of converting back into an `Int`. That's a pretty significant breaking change, and at the very least would introduce usage of `Maybe` in the constructor of the hobbled Int type.

Option 3: keep choseInt but throw a `Maybe` or `Either` into its type to check the range. Also pretty ugly.

4: Yet another option (maybe the most "right" one?) would be to have the math be done on 53 bit integers, using a different set of constants. I guess you set a 53 bit seed, then? If people are interested in going down this path, I'm willing to do the reading and try to figure things out, but it's new territory for me, and if there's someone else around more experienced with doing this kind of thing, I'd be very happy to defer.

5: Cheat a bit and use system random numbers? Lie about it in the type system? Somehow I don't suspect people will like that one...

As far as checking the resulting output goes, I've put together a very primitive and grossly inefficient chisquared lib here: https://github.com/matthewleon/purescript-chisquared

It should probably be supplemented by checking results in a more reliable statistical tool...

===

In any case, I think this issue deserves some discussion among the more experienced members of the project.

**Comment by hdgarrood** [comment]
Thanks for your thorough investigation! I'm a bit busy with uni work at the moment, but I'll try to get around to looking at this soon.

**Comment by matthewleon** [comment]
I'll take another look at it too. A few ideas came to me and I'm finding
the subject matter fascinating.

**Comment by matthewleon** [comment]
@paf31 I am looking at the following commit: https://github.com/purescript/purescript-quickcheck/commit/b4a3a03d015671bf43a7339e3f75633385ddaf5d

I can see that in it you changed `chooseInt` from a `choose`-based implementation to the current one. Can you explain why that was done? It seems that even ignoring the Int issues, there is also the issue that if the size of the difference in parameters gets large enough, the modulo arithmetic will cause the distribution to lose uniformity. I am guessing that despite this, you had a good reason for making the change. I just can't see it documented anywhere.

Otherwise, it seems to me that the old version would be better-behaved with large differences in the parameters.

**Comment by paf31** [comment]
I seem to remember it being something to do with the results being out of range, but I don't fully remember, sorry.
